### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by rnett**
The versions of ratpack and pac4j used here are both rather out of date.  We would like to use this in a project with the latest ratpack and pac4j versions, so this PR updates to them.

cc @davidmc24

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for this excellent contribution. It's merged.

I donwgraded the version to 4.0.0-SNAPSHOT as it does not require to follow the pac4j version.
I updated to JDK 11.
I updated the README.
I switched to Github Actions for CI.

Would you mind updating the demo as well: https://github.com/pac4j/ratpack-pac4j-demo?

**Comment by rnett** [comment]
Thanks, I'll update the demo.

Do you have plans for a release of 4.0.0?

**Comment by leleuj** [comment]
I'll do some tests with the demo and cut a release afterwards.

**Comment by leleuj** [comment]
I ran the demo and things don't work.
When performing a CAS authentication, I get:

```java
RATPACK PAC4J DEMO 11:06:01.524 [ratpack-compute-1-4] ERROR o.p.demo.ratpack.RatpackPac4jDemo - Unexpected error
org.pac4j.core.exception.TechnicalException: Failed to get user profile
	at ratpack.pac4j.internal.Pac4jAuthenticator.lambda$handle$5(Pac4jAuthenticator.java:75) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at ratpack.exec.Promise.lambda$onError$11(Promise.java:389) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Promise.lambda$sync$2(Promise.java:146) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:534) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:259) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:252) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:188) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.doResume(DefaultExecution.java:580) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.lambda$resume$0(DefaultExecution.java:573) ~[ratpack-exec-1.9.0.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:137) ~[ratpack-exec-1.9.0.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: ratpack.session.NonAllowedSessionTypeException: Type org.pac4j.cas.profile.CasProfile is not an allowed session type. Register a SessionTypeFilterPlugin allowing it. See SessionModule.allowTypes().
	at ratpack.session.SessionTypeFilter.assertAllowed(SessionTypeFilter.java:59) ~[ratpack-session-1.9.0.jar:na]
	at ratpack.session.internal.JavaBuiltinSessionSerializer$TypeFilteringObjectOutputStream.writeClassDescriptor(JavaBuiltinSessionSerializer.java:55) ~[ratpack-session-1.9.0.jar:na]
	at java.base/java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1283) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1232) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1428) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at java.base/java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:333) ~[na:na]
	at java.base/java.util.HashMap.writeObject(HashMap.java:1411) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at ratpack.session.internal.JavaBuiltinSessionSerializer.serialize(JavaBuiltinSessionSerializer.java:29) ~[ratpack-session-1.9.0.jar:na]
	at ratpack.session.internal.DefaultSession$Data.set(DefaultSession.java:312) ~[ratpack-session-1.9.0.jar:na]
	at ratpack.session.SessionData.set(SessionData.java:268) ~[ratpack-session-1.9.0.jar:na]
	at ratpack.pac4j.internal.RatpackSessionStore.lambda$set$1(RatpackSessionStore.java:39) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at ratpack.util.Exceptions.uncheck(Exceptions.java:111) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.pac4j.internal.RatpackSessionStore.set(RatpackSessionStore.java:39) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at org.pac4j.core.profile.ProfileManager.saveAll(ProfileManager.java:157) ~[pac4j-core-5.1.4.jar:na]
	at org.pac4j.core.profile.ProfileManager.save(ProfileManager.java:144) ~[pac4j-core-5.1.4.jar:na]
	at ratpack.pac4j.internal.Pac4jAuthenticator.lambda$handle$3(Pac4jAuthenticator.java:67) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
	at ratpack.pac4j.internal.Pac4jAuthenticator.lambda$handle$4(Pac4jAuthenticator.java:67) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at ratpack.exec.Promise.lambda$map$16(Promise.java:550) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Downstream$1.success(Downstream.java:73) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:52) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Downstream$2.success(Downstream.java:104) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.AsyncDownstream.lambda$success$1(AsyncDownstream.java:56) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:507) ~[ratpack-exec-1.9.0.jar:na]
	... 13 common frames omitted
```

When I click on the "SAML link", I get:

```java
RATPACK PAC4J DEMO 11:06:56.474 [ratpack-compute-1-6] WARN  org.apache.velocity.deprecation - configuration key 'resource.loader' has been deprecated in favor of 'resource.loaders'
RATPACK PAC4J DEMO 11:06:56.477 [ratpack-compute-1-6] INFO  o.p.s.c.DefaultSignatureSigningParametersProvider - Created signature signing parameters.
Signature algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
Signature canonicalization algorithm: http://www.w3.org/2001/10/xml-exc-c14n#
Signature reference digest methods: http://www.w3.org/2001/04/xmlenc#sha512
RATPACK PAC4J DEMO 11:06:56.489 [ratpack-compute-1-6] ERROR o.p.demo.ratpack.RatpackPac4jDemo - Unexpected error
org.pac4j.core.exception.TechnicalException: Failed to redirect
	at ratpack.pac4j.RatpackPac4j.lambda$initiateAuthentication$19(RatpackPac4j.java:587) ~[ratpack-pac4j-4.0.0-SNAPSHOT.jar:na]
	at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:52) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Promise.lambda$map$16(Promise.java:551) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Downstream$1.success(Downstream.java:73) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Promise.lambda$value$5(Promise.java:231) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:507) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:259) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:252) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:188) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecController$1.start(DefaultExecController.java:191) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.handling.internal.DefaultContext.start(DefaultContext.java:101) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.NettyHandlerAdapter.newRequest(NettyHandlerAdapter.java:183) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:92) ~[ratpack-core-1.9.0.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:137) ~[ratpack-exec-1.9.0.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
RATPACK PAC4J DEMO 11:06:56.495 [ratpack-compute-1-6] WARN  r.file.internal.ResponseTransmitter - attempt at double transmission for: /saml2/index.html
ratpack.handling.internal.DoubleTransmissionException: attempt at double transmission for: /saml2/index.html
	at ratpack.server.internal.DefaultResponseTransmitter.pre(DefaultResponseTransmitter.java:154) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.DefaultResponseTransmitter.transmit(DefaultResponseTransmitter.java:179) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.DefaultResponseTransmitter.transmit(DefaultResponseTransmitter.java:168) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.http.internal.DefaultResponse.lambda$commit$4(DefaultResponse.java:347) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.http.internal.DefaultResponse.finalizeResponse(DefaultResponse.java:364) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.http.internal.DefaultResponse.finalizeResponse(DefaultResponse.java:384) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.http.internal.DefaultResponse.lambda$finalizeResponse$7(DefaultResponse.java:381) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultOperation.lambda$then$0(DefaultOperation.java:46) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:52) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.Downstream$2.success(Downstream.java:104) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.AsyncDownstream.lambda$success$1(AsyncDownstream.java:56) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:507) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:259) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:252) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:188) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.exec.internal.DefaultExecController$1.start(DefaultExecController.java:191) ~[ratpack-exec-1.9.0.jar:na]
	at ratpack.handling.internal.DefaultContext.start(DefaultContext.java:101) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.NettyHandlerAdapter.newRequest(NettyHandlerAdapter.java:183) ~[ratpack-core-1.9.0.jar:na]
	at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:92) ~[ratpack-core-1.9.0.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:137) ~[ratpack-exec-1.9.0.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

@rnett did you test the demo?

**Comment by rnett** [comment]
I tested the Google OAuth, but that's the only one I have an account for.  Can I test the SAML one without Okta?

The CAS failure looks like it just needs to be added [here](https://github.com/pac4j/ratpack-pac4j-demo/blob/master/src/main/java/org/pac4j/demo/ratpack/RatpackPac4jDemo.java#L90).

The SAML one looks like it may be a bug, I'll look into it if I can get SAML working (see first line).

**Comment by rnett** [comment]
Tried out SAML, the failure happens before redirecting you to the provider so I can reproduce it.  The issue is that `client.getRedirectionAction(webContext, webContext.getSessionStore())` for the SAML client returns an OK response with a bunch of HTTP code (with something about "Since your browser does not support JavaScript, you must press the Continue button once to proceed." which is odd because JS is definitely supported), which is definitely not a redirect, and so ratpack doesn't know how to handle it.  How is that supposed to be handled?

**Comment by rnett** [comment]
Ok, the issue here is that I wasn't handling the Ok response of `getRedirectionAction` since I didn't think Ok was a possible redirect action.  Fixing that fixes the SAML issue.  I'm making a PR for that and the double response issue.

I don't have accounts for most of the providers, so I can't do this myself, but you or someone should test each auth provider and add the necessary session classes [here](https://github.com/pac4j/ratpack-pac4j-demo/blob/master/src/main/java/org/pac4j/demo/ratpack/RatpackPac4jDemo.java#L90).  I'm adding each of the client's profile types, but there may be others (i.e. types used as attributes).

**Comment by leleuj** [comment]
OK. Waiting for your PR. Then, I'll re-test all providers after adding the correct types where needed.

**Comment by rnett** [comment]
👍 
PR: https://github.com/pac4j/ratpack-pac4j/pull/7

**Comment by rnett** [comment]
Looking at the demo code, I'd start with:
```
CommonProfile.class, 
BasicUserProfile.class, 
CasProfile.class,
OidcProfile.class,
SAML2Profile.class,
FacebookProfile.class,
TwitterProfile.class,
JwtProfile.class
```

**Comment by leleuj** [comment]
I'm testing the demo and I need to add many types as allowed for the session.

In progress:
```java
                            SessionModule.allowTypes(binder(), CommonProfile.class,
                                BasicUserProfile.class,
                                CasProfile.class,
                                OidcProfile.class,
                                SAML2Profile.class,
                                FacebookProfile.class,
                                TwitterProfile.class,
                                JwtProfile.class,
                                OAuth1RequestToken.class,
                                OAuth1Token.class,
                                Token.class,
                                OAuth10Profile.class,
                                OAuth20Profile.class,
                                URI.class,
                                Date.class,
                                Color.class);
```

I'm a bit surprised, is it normal? can I allow anything?

**Comment by leleuj** [comment]
I'm now stuck on the `java.time.Ser` class which is not allowed and which I can't register...

**Comment by rnett** [comment]
It's from the new version of ratpack, as far as I know there's no way to allow everything.  It's expected, but at the same time most uses won't need to add that many (we only needed `Google2Profile.class, URI.class, Locale.class` for Google OAuth).

**Comment by leleuj** [comment]
I have seen that but I don't know how to use it: https://ratpack.io/manual/current/api/ratpack/session/SessionTypeFilter.html#unsafeAllowAll()

**Comment by rnett** [comment]
`binder().bind(SessionTypeFilter.class).toInstance(SessionTypeFilter.unsafeAllowAll());` seems to work.  Probably fine for a demo.

**Comment by leleuj** [comment]
Good. Almost everything works.

I still have one problem with the form authentication: login==password works as a successful authentication. But when it fails (login!=password), it stays on the 303 response. The "Location" header is missing (for example: http://localhost:8080/loginForm?username=fds&error=CredentialsException).

**Comment by rnett** [comment]
Found the issue, fixed it in https://github.com/pac4j/ratpack-pac4j/pull/13.  Not sure why it's only happening now, but I guess something with HttpAction changed.

**Comment by leleuj** [comment]
Excellent! The fix works. I just released ratpack-pac4j v4.0.0. It will show up in the Maven central repository within a few hours.

**Comment by rnett** [comment]
🎉 Thanks for the help!

**Comment by leleuj** [comment]
Thanks for your help too.

**Pull request merged**
