### PR TITLE
Update Pac4j to 6.0.0

### PR DESCRIPTION
**Pull request by rnett**
This PR updates Pac4j to 6.0.0, making the necessary changes to the ratpack integration to allow it to continue to work.

There's a companion PR for the demo here:  https://github.com/pac4j/ratpack-pac4j-demo/pull/23

I'm not going to be terribly responsive over the holidays, so there's no rush.  @jthurne and @gcoopercos can cover some of the time for me.

### CODE REVIEW

**Comment by rnett** [comment]
cc @jthurne @gcoopercos

**Comment by leleuj** [comment]
LGTM. Merging

**Comment by rnett** [comment]
@leleuj could you publish a new release for 5.0.0, or point me at how to?  I only see snapshot versions so far.

**Comment by leleuj** [comment]
Sure. I will do that very soon. I still plan the pac4j v6.0.1 release with bufixes before.

**Comment by rnett** [comment]
Great, thanks!

**Comment by leleuj** [comment]
`ratpack-pac4j` v5 has been released.

**Comment by rnett** [comment]
Wonderful, thanks again!

**Pull request merged**
